### ISSUE TITLE
Emoji picker opens but emojis cannot be picked (nothing happens upon clicking)

### ISSUE THREAD

**Issue by TClockBroughtMeHere** [mijorus/smile#78]
The emoji picker opens fine, but nothing happens when you click on the emoji. Some stats:

Desktop: Cinnamon 6.0.4, Gtk: GTK 3.24.33 wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia

**Comment by mijorus** [comment]
Sorry I've been quite busy lately.
Starting from 2.9.3, Smile is now using wl-clipboard under Wayland to copy emojis to the clipboard. This might be causing the issues you are describing.

I'll try to reproduce this bug as soon as I can

**Comment by mijorus** [comment]
@TClockBroughtMeHere I guess you are under xorg, right?

**Comment by TClockBroughtMeHere** [comment]
> @TClockBroughtMeHere I guess you are under xorg, right?

Yeah, that's right, I'm using xorg.

**Comment by mijorus** [comment]
I have released an update right now, there was a bug that was preventing the buttons from being clickable. Not sure if it is related though, please let me know if version 2.9.4 fixes the issue for you

**Comment by TClockBroughtMeHere** [comment]
> I have released an update right now, there was a bug that was preventing the buttons from being clickable. Not sure if it is related though, please let me know if version 2.9.4 fixes the issue for you

Thanks. Sadly, nothing appears to have changed, emojis still don't get inserted.

**Comment by mijorus** [comment]
> > I have released an update right now, there was a bug that was preventing the buttons from being clickable. Not sure if it is related though, please let me know if version 2.9.4 fixes the issue for you
> 
> Thanks. Sadly, nothing appears to have changed, emojis still don't get inserted.

Ok wait...  if you are talking about the fact that emojis don't get inserted when you select them, that is to be expected if you are under Wayland.

Apps cannot paste content on other apps, that's a limitation of the Wayland protocol at the moment

**Comment by TClockBroughtMeHere** [comment]
> > > I have released an update right now, there was a bug that was preventing the buttons from being clickable. Not sure if it is related though, please let me know if version 2.9.4 fixes the issue for you
> > 
> > 
> > Thanks. Sadly, nothing appears to have changed, emojis still don't get inserted.
> 
> Ok wait... if you are talking about the fact that emojis don't get inserted when you select them, that is to be expected if you are under Wayland.
> 
> Apps cannot paste content on other apps, that's a limitation of the Wayland protocol at the moment

I'm using X or Xorg, not Wayland. Sorry if I got the terms mixed up (tho I don't think so?). I'm using Linux Mint 21.3. and Wayland isn't enabled by default in Linux Mint (for a long time if I understand correctly).

**Comment by GordonZed** [comment]
Could it be something like xclip or xsel? Actually, that doesn't really make sense, since the clipboard management part is built in...

It would be nice if there was an option to have the Emoji sent to stdout instead for cases like this. Then the output could just be piped to something like xsel to manage the clipboard part. Probably great for tiling window manager users. I'm on i3, and while it's definitely quicker than Googling "shrug emoji" and copy-pasting it, I haven't managed to get it to paste automatically either.

**Comment by joaoportela** [comment]
I have the same issue.

I'm running x11:
```
$ loginctl show-session $(loginctl|grep $(whoami) |awk '{print $1}') -p Type
Type=x11
```

Version:
```
$ flatpak run it.mijorus.smile --version
2.9.4
```

Any flag I can enable for debug logs or something?

**Comment by milindpatel63** [comment]
i'm having the same issue. I'm running latest Pop OS with smile running in flatpak.

**Comment by milindpatel63** [comment]
> > i'm having the same issue. I'm running latest Pop OS with smile running in flatpak.
> 
> Can you post information about your build? Like a `neofetch` output, wayland or xorg, flatpak version, etc.
> 
> What happens if you:
> 
> > Preferences > "Paste emojis automatically" > Enabled > toggle off/on

nvm. I enabled the "Run in background", and it seems to have solved my issue. Maybe smile was quitting before copying into clipboard.
Here's my neofetch anyways
```
             /////////////                user@diana-pop-os 
         /////////////////////            -------------------------- 
      ///////*767////////////////         OS: Pop!_OS 22.04 LTS x86_64 
    //////7676767676*//////////////       Host: TUF Gaming FX505DT_FX505DT 1.0 
   /////76767//7676767//////////////      Kernel: 6.9.3-76060903-generic 
  /////767676///*76767///////////////     Uptime: 2 hours, 37 mins 
 ///////767676///76767.///7676*///////    Packages: 2906 (dpkg), 66 (flatpak),  
/////////767676//76767///767676////////   Shell: bash 5.1.16 
//////////76767676767////76767/////////   Resolution: 1920x1080 
///////////76767676//////7676//////////   DE: GNOME 42.9 
////////////,7676,///////767///////////   WM: Mutter 
/////////////*7676///////76////////////   WM Theme: Nordic-darker-v40 
///////////////7676////////////////////   Theme: Nordic-darker-v40 [GTK2/3] 
 ///////////////7676///767////////////    Icons: Pop [GTK2/3] 
  //////////////////////'////////////     Terminal: gnome-terminal 
   //////.7676767676767676767,//////      CPU: AMD Ryzen 5 3550H with Radeon Ve 
    /////767676767676767676767/////       GPU: NVIDIA GeForce GTX 1650 Mobile / 
      ///////////////////////////         GPU: AMD ATI Radeon Vega Series / Rad 
         /////////////////////            Memory: 8700MiB / 13911MiB 
             /////////////
                                                                  
                                                                  


```
Running Flatpak 1.14.6

**Comment by infinite-ram** [comment]
Enabling "Run in the background" in preferences solved this issue for me:

![Image](https://github.com/user-attachments/assets/e00a9d01-e6c3-46a4-964d-dba86e9f5ecd)

**Comment by evandro777** [comment]
I'm having the same issue on Mint 21.3. I already tried enabling `Run in the background`, but didn't work.
Also, `Paste emojis automatically`, Status: ✅

```
OS: Linux Mint 21.3 x86_64
Kernel: 6.8.0-52-generic
DE: Cinnamon 6.4.6
WM: Mutter (Muffin)
```

**Comment by MinuteNewt** [comment]
I've been using [Emote](https://flathub.org/apps/com.tomjwatson.Emote) instead. I've set the launch shortcut to Alt plus . (period) and it opens every time. The downside is that each time you select the emoji, it closes (you have to choose the emojis one by one), but I'm willing to live with that. 

Not sure if anything is being done to fix the issues Smile is having. I know this is a FOSS project and I'm not being ungrateful. As @evdcush said above, we are free to not use this app and since I don't know how to fix the bug Smile has myself, I'll just use another programme. No hard feelings. Hope Smile gets fixed eventually.
